package com.holopengin.instantjpdict

import com.holopengin.instantjpdict.util.KanaOrthography
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

// #75: the pre-reform (旧仮名遣い) lookup-query normaliser. The table is the committed
// asset generated by tools/build_kana_variants.py from JMdict's own kana
// cross-references, so the pairs are asserted against the file: a change to the table
// or a mistyped Kotlin literal fails here rather than silently changing lookups.
//
// Query-side only: nothing in this test asserts anything about displayed text, because
// the normaliser never touches it — the caller searches the raw prefix alongside the
// normalised one.
class KanaOrthographyTest {

    private fun table() = KanaOrthography.parse(
        TestAssets.assetsFile("variants/kana_variants.txt").readText()
    )

    @Before
    fun installTheCommittedTable() {
        KanaOrthography.install(table())
    }

    /** Every row member the committed table ships, pinned so an edit is visible. */
    private val shippedPairs = mapOf(
        // wagyou ワ行
        'ゐ' to 'い', 'ゑ' to 'え', 'ヰ' to 'イ', 'ヱ' to 'エ',
        // dakugyou だ行
        'ぢ' to 'じ', 'づ' to 'ず', 'ヂ' to 'ジ', 'ヅ' to 'ズ',
        // sokuon 促音
        'つ' to 'っ', 'ツ' to 'ッ',
        // yoon 拗音
        'や' to 'ゃ', 'ゆ' to 'ゅ', 'よ' to 'ょ', 'ヤ' to 'ャ', 'ユ' to 'ュ', 'ヨ' to 'ョ',
    )

    @Test
    fun parses_the_committed_asset() {
        val lines = TestAssets.assetsFile("variants/kana_variants.txt")
            .readText().lines().count { it.isNotBlank() && !it.startsWith("#") }
        assertEquals(16, lines)
        assertEquals(16, table().size)
    }

    @Test
    fun pins_every_shipped_pair() {
        val t = table()
        for ((variant, canonical) in shippedPairs) {
            assertEquals(canonical, t.canonical(variant))
        }
        // Excluded as ordinary modern usage, so they fold to themselves: the
        // accusative particle, and the 小書き row (あ->ぁ … わ->ゎ), whose variant
        // side is a standard modern kana.
        assertEquals('を', t.canonical('を'))
        assertEquals('ヲ', t.canonical('ヲ'))
        for (ordinary in "あいうえおわアイウエオワ") {
            assertEquals(ordinary, t.canonical(ordinary))
        }
    }

    @Test
    fun installs_and_normalises_with_the_asset() {
        KanaOrthography.install(table())
        assertEquals(16, KanaOrthography.entryCount)
    }

    @Test
    fun normalises_the_headline_legacy_forms() {
        // いつしよ -> いっしょ needs つ->っ AND よ->ょ; the size model can do neither,
        // because neither half is a size change on its own.
        assertEquals("いっしょ", KanaOrthography.modernise("いつしよ"))
        // しゆつぱつ -> しゅっぱつ needs つ->っ AND ゆ->ゅ.
        assertEquals("しゅっぱつ", KanaOrthography.modernise("しゆつぱつ"))
        assertEquals("ちょっと", KanaOrthography.modernise("ちよつと"))
        // きやう -> きょう is only half reached: や->ゃ is a 拗音 size row this table
        // carries, but the アウ->オウ vowel shift is a different alternation (や->よ)
        // that JMdict does not record as a kana variant at all, so it is out of
        // scope here and the result stays きゃう. Reported as a known gap.
        assertEquals("きゃう", KanaOrthography.modernise("きやう"))
    }

    @Test
    fun normalises_wagyou_and_dakugyou_in_context() {
        assertEquals("いる", KanaOrthography.modernise("ゐる"))
        assertEquals("植えた", KanaOrthography.modernise("植ゑた"))
        assertEquals("あずま", KanaOrthography.modernise("あづま"))
        assertEquals("おのずから", KanaOrthography.modernise("おのづから"))
        assertEquals("みず", KanaOrthography.modernise("みづ"))
        assertEquals("はなじ", KanaOrthography.modernise("はなぢ"))
        assertEquals("ウイスキー", KanaOrthography.modernise("ウヰスキー"))
        assertEquals("エビス", KanaOrthography.modernise("ヱビス"))
    }

    @Test
    fun leaves_rendaku_alone() {
        // 連濁: つづく/ちぢむ are the modern forms themselves. Folding them would break
        // correct lookups, which is why the row member checks the preceding character.
        assertEquals("つづく", KanaOrthography.modernise("つづく"))
        assertEquals("ちぢむ", KanaOrthography.modernise("ちぢむ"))
        assertEquals("ちぢれる", KanaOrthography.modernise("ちぢれる"))
        assertEquals("つづける", KanaOrthography.modernise("つづける"))
        // katakana counterpart of the same guard
        assertEquals("ツヅク", KanaOrthography.modernise("ツヅク"))
    }

    @Test
    fun leaves_the_accusative_particle_alone() {
        // を is ordinary modern usage. JMdict attests を->お only inside a handful of
        // lexical items, so it is not a row-wide rule; folding it would rewrite
        // 「本を読む」 into 「本お読む」 and lose the lookup it is meant to help.
        assertEquals("本を読む", KanaOrthography.modernise("本を読む"))
        assertEquals("ヲタク", KanaOrthography.modernise("ヲタク"))
    }

    @Test
    fun the_excluded_rows_fold_to_themselves() {
        // No table entry exists for these, so the normaliser is the identity on them.
        // They are excluded because their variant side is ordinary modern usage:
        // 小書き (あ->ぁ) is gairaigo spelling, and shipping it changed 1,220 positions
        // on the modern slice — 977 clipping a reachable headword — while repairing
        // nothing extra on the legacy one.
        assertEquals("ああ", KanaOrthography.modernise("ああ"))
        assertEquals("そうそう", KanaOrthography.modernise("そうそう"))
        assertEquals("かわ", KanaOrthography.modernise("かわ"))
        assertEquals("コーヒー", KanaOrthography.modernise("コーヒー"))
    }

    @Test
    fun does_not_fold_tsu_before_the_k_row() {
        // Measured: つ before か行 (つかう, つくえ) clipped more modern words than it
        // repaired, so 促音 fires only before た行/さ行/ぱ行.
        assertEquals("つかう", KanaOrthography.modernise("つかう"))
        assertEquals("つくえ", KanaOrthography.modernise("つくえ"))
        // ...while the sokuon positions still normalise
        assertEquals("あった", KanaOrthography.modernise("あつた"))
        assertEquals("いって", KanaOrthography.modernise("いつて"))
        assertEquals("いっぱい", KanaOrthography.modernise("いつぱい"))
    }

    @Test
    fun is_the_identity_on_modern_text() {
        for (modern in listOf("", "あ", "ABC", "日本語", "つくえ", "にっぽん", "がっこう",
                              "コーヒー", "12月", "、。")) {
            assertEquals(modern, KanaOrthography.modernise(modern))
        }
    }

    @Test
    fun is_deterministic_and_answers_from_the_query_alone() {
        // No page-ratio gate and no document-wide heuristic: the answer depends on the
        // queried string, so a word normalises the same inside a sentence as alone.
        val q = "いつしよ"
        assertEquals(KanaOrthography.modernise(q), KanaOrthography.modernise(q))
        assertEquals("いっしょ", KanaOrthography.modernise(q))
        assertEquals("行っていっしょ", KanaOrthography.modernise("行つていつしよ"))
        assertEquals("。いっしょ、", KanaOrthography.modernise("。いつしよ、"))
        assertEquals("いる", KanaOrthography.modernise("ゐる"))
    }

    @Test
    fun unknown_characters_fold_to_themselves() {
        val t = table()
        assertEquals('漢', t.canonical('漢'))
        assertEquals('ん', t.canonical('ん'))
        assertEquals('A', t.canonical('A'))
        assertEquals('い', t.canonical('い'))
    }

    @Test
    fun empty_table_is_the_identity() {
        val t = KanaOrthography.parse("")
        assertEquals(0, t.size)
        assertEquals('ゐ', t.canonical('ゐ'))
        KanaOrthography.install(t)
        assertEquals("ゐる", KanaOrthography.modernise("ゐる"))
        KanaOrthography.install(table())
    }

    @Test
    fun parse_skips_malformed_lines_and_keeps_the_first_canonical() {
        val t = KanaOrthography.parse(
            """
            # a comment
            ゐ	い
            ゐ	ゑ
            ゐい
            い	い
            ゐ	い	extra
            """.trimIndent() + "\n"
        )
        assertEquals(1, t.size)
        assertEquals('い', t.canonical('ゐ'))
    }

    @Test
    fun the_table_is_kana_only_single_characters() {
        val text = TestAssets.assetsFile("variants/kana_variants.txt").readText()
        for (raw in text.lineSequence()) {
            val line = raw.trim()
            if (line.isEmpty() || line.startsWith("#")) continue
            val parts = line.split('\t')
            assertEquals("2 columns: $line", 2, parts.size)
            assertTrue("single char: $line", parts[0].length == 1 && parts[1].length == 1)
            val o = parts[0][0].code
            assertTrue("kana row member: $line",
                o in 0x3041..0x3096 || o in 0x30A1..0x30F6)
        }
    }
}
