package com.holopengin.instantjpdict

import com.holopengin.instantjpdict.util.KanjiVariants
import org.junit.Assert.*
import org.junit.Test

// #44: the vendored Unihan variant table (kSemanticVariant + kZVariant), generated by
// tools/build_kanji_variants.py. Direction: variant -> canonical, where the canonical
// side is the character present in PP-OCRv6_small_ncnn/vocab.json and the variant is
// the one that is not. The pairs are asserted against the *committed asset*, so a
// change to the file or a mistyped Kotlin literal fails here.
class KanjiVariantsTest {

    private fun table() = KanjiVariants.parse(TestAssets.variantsFile().readText())

    @Test
    fun parses_the_committed_asset() {
        val lines = TestAssets.variantsFile().readText().lines().count { it.isNotBlank() }
        assertEquals(669, lines)
        // 600 distinct variants: Unihan gives 58 of them more than one canonical
        // candidate, and the table keeps every pair (the fold picks one — see
        // JapaneseUtilVariantFoldTest). 593 of the pairs come from Unihan's
        // kSemanticVariant/kZVariant; the other 76 come from JMdict's oK/rK tags
        // intersected with Unihan's simplified/traditional axis.
        assertEquals(600, table().size)
    }

    @Test
    fun the_jmdict_half_reaches_old_orthography_the_vocab_rule_could_not() {
        val t = table()
        // Both forms are emittable, so the original "canonical = the side present in
        // vocab.json" rule dropped these pairs outright — 摑 could be neither offered in
        // the popup nor folded onto the headword (#44 report).
        assertEquals('掴', t.canonical('摑'))
        assertEquals('国', t.canonical('國'))
        assertEquals('会', t.canonical('會'))
        assertEquals('灯', t.canonical('燈'))
        assertEquals('当', t.canonical('當'))
        // Traps the intersection exists to exclude: Unihan links each of these, but they are
        // different words in Japanese and JMdict never tags one as an old form of the other.
        assertEquals('誌', t.canonical('誌'))
        assertEquals('製', t.canonical('製'))
        // JMdict tags these as out-dated spellings of a *different* word (丈/たけ, 品/しな);
        // Unihan does not link the characters, so they stay out of the table.
        assertEquals('長', t.canonical('長'))
        assertEquals('階', t.canonical('階'))
    }

    @Test
    fun chains_resolve_to_the_form_a_dictionary_indexes() {
        val t = table()
        // 冩 -> 寫 -> 写: the fold is a single character pass, so a chain left 冩 pointing at
        // 寫, which no dictionary indexes. Both hops now reach 写.
        assertEquals('写', t.canonical('冩'))
        assertEquals('写', t.canonical('寫'))
        // A genuine cycle (干 <-> 乾) is kept as-is rather than guessed at.
        assertEquals('干', t.canonical('乾'))
        assertEquals('乾', t.canonical('干'))
    }

    @Test
    fun folds_variant_onto_the_dictionary_form() {
        val t = table()
        assertEquals('回', t.canonical('囘'))
        assertEquals('鬱', t.canonical('欝'))
        // the header pair the direction rule was validated on, plus a sample of the
        // most frequent remaining entries in the Aozora corpus
        assertEquals('罈', t.canonical('壜'))
        assertEquals('逃', t.canonical('迯'))
        assertEquals('器', t.canonical('噐'))
        assertEquals('慚', t.canonical('慙'))
    }

    @Test
    fun a_variant_with_several_canonical_candidates_keeps_them_all() {
        val t = table()
        // Unihan gives 葢 two candidates and 冫 two; the table is faithful to that and
        // canonical() returns the first by codepoint, which is arbitrary on purpose —
        // the measured fold picks the corpus-dominant form instead (葢 -> 蓋, 冫 -> 氷,
        // see JapaneseUtilVariantFoldTest)
        assertEquals(listOf('盖', '蓋'), t.canonicalsOf('葢'))
        assertEquals('盖', t.canonical('葢'))
        assertEquals(listOf('冰', '氷'), t.canonicalsOf('冫'))
        assertEquals('冰', t.canonical('冫'))
        // single-candidate variants are the rule, not the exception (464 of 523)
        assertEquals(listOf('回'), t.canonicalsOf('囘'))
        assertTrue(t.canonicalsOf('あ').isEmpty())
    }

    @Test
    fun unknown_character_returns_itself() {
        val t = table()
        assertEquals('漢', t.canonical('漢'))
        assertEquals('あ', t.canonical('あ'))
        assertEquals('A', t.canonical('A'))
        // the canonical side is not itself a fold target
        assertEquals('回', t.canonical('回'))
    }

    @Test
    fun obsolete_forms_are_the_reverse_direction() {
        val t = table()
        assertTrue('囘' in t.obsoleteFormsOf('回'))
        assertTrue('欝' in t.obsoleteFormsOf('鬱'))
        // both Unihan candidates for 罈 — the table keeps every pair the file has
        assertEquals(listOf('墰', '壜'), t.obsoleteFormsOf('罈'))
        // sorted, and a character with no known variant has none
        assertEquals(t.obsoleteFormsOf('回').sorted(), t.obsoleteFormsOf('回'))
        assertTrue(t.obsoleteFormsOf('あ').isEmpty())
        assertTrue(t.obsoleteFormsOf('漢').isEmpty())
    }

    @Test
    fun empty_table_is_the_identity() {
        val t = KanjiVariants.parse("")
        assertEquals(0, t.size)
        assertEquals('囘', t.canonical('囘'))
        assertTrue(t.obsoleteFormsOf('回').isEmpty())
    }

    @Test
    fun parse_skips_malformed_lines_and_keeps_the_first_canonical() {
        val t = KanjiVariants.parse(
            """
            # a comment
            你	你
            囘	回
            囘	囬
            囘	回	extra
            囘回
            回	回
            """.trimIndent() + "\n"
        )
        // only the well-formed single-character pairs survive; duplicate variant keeps
        // the first line (the generator sorts, so that is the lowest codepoint)
        assertEquals(1, t.size)
        assertEquals('回', t.canonical('囘'))
    }
}
