package com.holopengin.instantjpdict.util

import android.content.Context
import kotlin.math.ln

/**
 * Kanji component table (KRADFILE) — the visual bridge between what the recogniser
 * *saw* at an unemittable glyph and what a dictionary can *offer* for it (#44).
 *
 * At the `呟` gap the head's top-5 is `咳 咬 啦 哮 眩` — all 口/亠 characters — while
 * `呟` itself decomposes to `亠 口 幺 玄`. Sharing components is what selects the right
 * candidate; a text n-gram cannot separate `呟` from `咲`/`働` in context, but the
 * components can. The table therefore carries both directions:
 *
 *  - [componentsOf] — the decomposition of one character (generation / filtering),
 *  - [kanjiWith] — the inverted index `component -> kanji` (a precomputed posting
 *    list, never a scan of the whole table per call),
 *  - [idfOf] — how *informative* a component is (`ln(kanjiCount / kanjiContaining)`),
 *    so sharing `車` can be weighed against sharing `一`.
 *
 * ## Provenance
 *
 * The asset [ASSET_PATH] is a merged, vendored copy of EDRDG **KRADFILE** and
 * **KRADFILE2** (`http://ftp.edrdg.org/pub/Nihongo/kradzip.zip`; copyright 2001/2007
 * Michael Raine, James Breen and the Electronic Dictionary Research and Development
 * Group; licensed **CC BY-SA 4.0**). 12,156 entries, one line per kanji —
 * `呟:亠 口 幺 玄` — LF endings, sorted by codepoint. The sibling `PROVENANCE.txt`
 * records the entry count, byte size and SHA-256.
 *
 * **The file is generated by `tools/build_component_table.py` and must never be
 * hand-edited** — rerun the tool instead, so the SHA-256 in `PROVENANCE.txt` keeps
 * matching. [parse] is pure (no Android dependency) so tests can exercise it against
 * the real file or an inline fixture; [load] is the only Android half.
 */
class ComponentTable private constructor(
    /** kanji -> its components, in the asset's order. */
    private val components: Map<Char, List<Char>>,
    /** component -> every kanji carrying it, ascending by codepoint. */
    private val inverted: Map<Char, List<Char>>,
    /** component -> inverse document frequency over the kanji in this table. */
    private val idf: Map<Char, Float>,
) {

    /** Number of entries parsed — every key in the asset. */
    val entryCount: Int get() = components.size

    /**
     * Number of kanji in the table — the population the IDF is computed over, so that
     * a stray non-ideograph key (there is none in the shipped asset) cannot shift
     * every weight.
     */
    val kanjiCount: Int get() = components.keys.count { isKanji(it) }

    /** Number of distinct components seen in the table. */
    val componentCount: Int get() = inverted.size

    /**
     * The components of [ch], or an empty list for a character the table has no entry
     * for. Never throws: an unknown character is simply no evidence, and every caller
     * in the proposal path (filter, majority vote, neighbours) treats an empty
     * decomposition as "this character contributes nothing".
     */
    fun componentsOf(ch: Char): List<Char> = components[ch] ?: emptyList()

    /** Whether the table has an entry for [ch]. */
    fun hasComponents(ch: Char): Boolean = components.containsKey(ch)

    /**
     * Every kanji carrying **all** of [all] — the strict component filter the
     * deletion path measured at 229 -> 7 candidates with the right character surviving.
     *
     * Backed by the precomputed inverted index: the smallest posting list among the
     * requested components is filtered by the remaining ones, so the call is
     * proportional to the rarest component's set rather than to the whole table.
     *
     * Two deliberate choices, both mirroring the measured filter `comps and comps <=
     * set(table[c])` in `oov_component_probe.py`:
     *  - an **empty requirement returns nothing** (no evidence is not a licence to
     *    return all 12,156 kanji),
     *  - a component **no kanji carries** (unknown, or itself not a component) yields
     *    an empty result rather than being ignored.
     *
     * Result is ascending by codepoint and free of duplicates; [all] may repeat a
     * component without changing the result.
     */
    fun kanjiWith(all: List<Char>): List<Char> {
        if (all.isEmpty()) return emptyList()
        var smallest: List<Char>? = null
        for (c in all) {
            val posting = inverted[c] ?: return emptyList()
            if (posting.isEmpty()) return emptyList()
            if (smallest == null || posting.size < smallest.size) smallest = posting
        }
        val required = all.toSet()
        val candidates = smallest ?: return emptyList()
        val out = ArrayList<Char>(minOf(candidates.size, 256))
        for (k in candidates) {
            val comps = components[k] ?: continue
            if (required.all { it in comps }) out.add(k)
        }
        return out
    }

    /**
     * `ln(kanjiCount / kanjiCountContaining(component))` — nats, not bits.
     *
     * A component carried by few kanji is strong evidence; `一` (most of the table)
     * is nearly worthless. An unknown component returns `0f`, mirroring the reference
     * `idf.get(c, 0.0)`: it adds no weight and can never make a fraction NaN.
     */
    fun idfOf(component: Char): Float = idf[component] ?: 0f

    /** All kanji in the table, ascending by codepoint (asset order). */
    fun allKanji(): List<Char> = components.keys.toList()

    companion object {

        /** Path of the vendored table inside `src/main/assets`. */
        const val ASSET_PATH = "components/krad_components.txt"

        private val CACHE_LOCK = Any()

        @Volatile
        private var cached: ComponentTable? = null

        /**
         * Parse the table from its text form. Pure — no Android, no I/O — so unit
         * tests exercise the same code the device runs.
         *
         * Tolerant by design: a line without a single-character key or with no
         * parseable component is skipped rather than crashing the app, because this
         * parses a shipped asset. The unit test pinning the entry count (12,156) is
         * what makes a corrupted asset fail loudly.
         *
         * The **first** entry for a key wins, mirroring the generator's `setdefault`
         * in `tools/build_component_table.py`; components are de-duplicated within a
         * line, which is what the generator does too.
         */
        fun parse(text: String): ComponentTable {
            val table = LinkedHashMap<Char, List<Char>>()
            for (line in text.lineSequence()) {
                // Key is exactly one character; a blank or comment line has no colon
                // at index 1, so this also skips anything malformed at the front.
                if (line.length < 2 || line[1] != ':') continue
                val key = line[0]
                if (table.containsKey(key)) continue
                val comps = LinkedHashSet<Char>()
                for (token in line.substring(2).split(' ')) {
                    if (token.length == 1) comps.add(token[0])
                }
                if (comps.isNotEmpty()) table[key] = comps.toList()
            }

            // The IDF universe is the kanji subset, mirroring odp.kanji() in the
            // probe: the table is KRADFILE, so today that is all of it, but a stray
            // non-ideograph key must not shift every weight.
            val kanjiCount = table.keys.count { isKanji(it) }
            val posting = LinkedHashMap<Char, MutableList<Char>>()
            for ((kanji, comps) in table) {
                if (!isKanji(kanji)) continue
                for (c in comps) posting.getOrPut(c) { ArrayList() }.add(kanji)
            }
            // Posting lists are sorted once here (the asset already is) so that
            // kanjiWith and neighboursOf return codepoint order without re-sorting.
            val inverted = LinkedHashMap<Char, List<Char>>(posting.size * 2)
            val idf = HashMap<Char, Float>(posting.size * 2)
            for ((c, carriers) in posting) {
                inverted[c] = carriers.sorted()
                idf[c] = ln(kanjiCount.toDouble() / carriers.size).toFloat()
            }

            return ComponentTable(table, inverted, idf)
        }

        /**
         * The table from the bundled asset, parsed on first use and cached
         * process-wide (later calls are a volatile read).
         *
         * The asset is ~266 KB / 12,156 lines, so **call this off the main thread**
         * (a coroutine on `Dispatchers.IO`, or a worker) — the read and parse are the
         * only work in this class that touches the device.
         */
        fun load(context: Context): ComponentTable {
            cached?.let { return it }
            synchronized(CACHE_LOCK) {
                cached?.let { return it }
                val text = context.applicationContext.assets
                    .open(ASSET_PATH)
                    .use { it.readBytes().toString(Charsets.UTF_8) }
                return parse(text).also { cached = it }
            }
        }

        /** CJK ideograph ranges, mirroring `odp.kanji` in the measurement probe. */
        private fun isKanji(c: Char): Boolean {
            val o = c.code
            return (o in 0x3400..0x4DBF) || (o in 0x4E00..0x9FFF) || (o in 0xF900..0xFAFF)
        }
    }
}
