package com.holopengin.instantjpdict.util

/**
 * One component of the bundled-licence index (#70): what it is, the licence it is
 * under, and the asset files that carry the licence text and attribution notice.
 *
 * Parsed from `assets/licenses/INDEX.txt`, which is generated by
 * `./gradlew :app:generateLicenseIndex` (see docs/licenses.md) — this class holds
 * only the reading side, so it stays free of Android types and is unit-testable.
 */
data class LicenseEntry(
    val name: String,
    /** Licence label as the index states it, e.g. "Apache-2.0". */
    val license: String,
    /** Version or revision, or null when the index has "-". */
    val version: String?,
    /** Asset paths (relative to `assets/`) holding the licence texts. */
    val textFiles: List<String>,
    /** Asset path of the attribution/provenance notice, or null. */
    val noticeFile: String?,
    /** Where the licence was verified from, as recorded in the index. */
    val provenance: String?,
) {
    /** One-line label for the component list. */
    fun summary(): String =
        if (version == null) "$name — $license" else "$name $version — $license"
}

object LicenseIndex {

    const val INDEX_ASSET = "licenses/INDEX.txt"

    private const val COLUMNS = 6

    /**
     * Parse an index file. `#` starts a comment, blank lines are ignored, and the
     * six columns are TAB-separated:
     *
     *   name | licence | version | licence text file(s) | notice file | provenance
     *
     * `-` means "absent" for version, notice and provenance; the version goes into
     * [LicenseEntry.textFiles] as a comma-separated list and may be empty for a
     * component whose only notice is its notice file (public-domain data).
     *
     * A malformed line throws rather than being skipped: the file is generated, so
     * a line that does not parse means the file in the APK is not the one the
     * build produced, and silently dropping it would hide a missing notice.
     */
    fun parse(index: String): List<LicenseEntry> {
        val entries = mutableListOf<LicenseEntry>()
        index.lineSequence().forEachIndexed { i, raw ->
            val line = raw.trimEnd('\r', '\n', ' ')
            if (line.isBlank() || line.startsWith("#")) return@forEachIndexed
            val cols = line.split('\t')
            require(cols.size >= COLUMNS) {
                "licenses/INDEX.txt line ${i + 1}: expected $COLUMNS tab-separated columns, got ${cols.size}"
            }
            val name = cols[0].trim()
            val license = cols[1].trim()
            require(name.isNotEmpty() && license.isNotEmpty()) {
                "licenses/INDEX.txt line ${i + 1}: empty component name or licence"
            }
            val texts = cols[3].split(',').map { it.trim() }.filter { it.isNotEmpty() && it != "-" }
            val notice = cols[4].trim().takeIf { it.isNotEmpty() && it != "-" }
            require(texts.isNotEmpty() || notice != null) {
                "licenses/INDEX.txt line ${i + 1}: '$name' has neither a licence text nor a notice"
            }
            entries += LicenseEntry(
                name = name,
                license = license,
                version = cols[2].trim().takeIf { it.isNotEmpty() && it != "-" },
                textFiles = texts,
                noticeFile = notice,
                provenance = cols[5].trim().takeIf { it.isNotEmpty() && it != "-" },
            )
        }
        return entries
    }

    /**
     * The text the viewer shows for one component: its identity, its licence, where
     * that licence was verified from, then the notice and the full licence text(s).
     *
     * [read] resolves an asset path to its contents — a lambda so this stays
     * JVM-testable and so a missing file degrades to a visible line rather than an
     * exception in the middle of the dialog.
     */
    fun render(entry: LicenseEntry, read: (String) -> String?): String {
        val sb = StringBuilder()
        sb.append(entry.name)
        entry.version?.let { sb.append("  ").append(it) }
        sb.append('\n')
        sb.append("Licence: ").append(entry.license).append('\n')
        entry.provenance?.let { sb.append("Licence verified from: ").append(it).append('\n') }
        val files = listOfNotNull(entry.noticeFile) + entry.textFiles
        if (files.isEmpty()) {
            sb.append("\nNo licence text is bundled for this component; see the notice above.\n")
            return sb.toString()
        }
        files.forEach { path ->
            sb.append('\n').append("----- ").append(path).append(" -----\n\n")
            sb.append(read(path) ?: "(not found in the APK: $path)\n")
            if (!sb.endsWith("\n")) sb.append('\n')
        }
        return sb.toString()
    }
}
