// The kanadiff kana-size model, run through the ncnn the app already links for OCR.
//
// Not a bespoke forward pass any more: the converted graph reproduces the model author's ten
// published validation logits to 3.8e-06 on the host (fp32), and the param/bin are generated by
// a pipeline that writes the weight stream itself and asserts its byte total.
//
// Three conversion defects are worth knowing, because all three produce *plausible* output
// instead of an error, and all three bit this model:
//
//   * onnx2ncnn wrote an int64 initializer's 8 raw bytes while the param told ncnn to read 4, so
//     every later block in the sequential .bin was read four bytes early. The symptom is a net
//     whose outputs sit in a narrow band, not scrambled garbage.
//   * `Convolution1D` is 2-D and takes its in-channel count from `bottom_blob.h`, so a 3-D input
//     that looks like 48 channels is silently read as one.
//   * fp16 is a floor, not a detail: stock options cost ~1.5e-03 on this model against an fp32
//     reference the artifact describes to 1e-06. The options are pinned below, deliberately.
//
// Graph, as the param expresses it:
//
//   win  : 40 int32 byte values -> byte_emb (256x32)          -> [40,32]
//   pos  : MemoryData 0..39     -> pos_block (40x16)          -> [40,16]
//   cat  : concat -> [40,48] ; permute -> [48,40] channels-first
//   conv1: 48->64 k=5 pad=2 relu ; conv2: 64->64 k=3 pad=1 relu ; max over positions -> [64]
//   base : int32 pair index -> base_emb (20x16) -> [16] ; concat -> [80]
//   fc1  : 80->128 relu ; fc2: 128->1 -> logit          (sigmoid gives p(big))
//
// Positions are run one per extractor call. The param declares no batch dimension, and keeping
// one position per run leaves the int32 Embed inputs and the position-axis Reduction unambiguous.
#include <jni.h>
#include <android/log.h>

#include <string>
#include <vector>

#include "ncnn/net.h"

#define LOG_TAG "KanaSize"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

namespace {

constexpr int SEQ = 40;          // window bytes per position
constexpr int PAIRS = 20;        // pair-table size, i.e. valid `base` values
constexpr int THREADS = 2;       // 40 positions of a 47k-param net: threads are not the lever

struct Model {
    ncnn::Net net;
};

Model* asModel(jlong h) { return reinterpret_cast<Model*>(h); }

}  // namespace

extern "C" {

JNIEXPORT jlong JNICALL
Java_com_holopengin_instantjpdict_KanaSizeNcnn_create(
        JNIEnv* env, jclass, jstring paramPath_, jstring binPath_) {
    const char* paramPath = env->GetStringUTFChars(paramPath_, nullptr);
    const char* binPath = env->GetStringUTFChars(binPath_, nullptr);
    std::string param = paramPath ? paramPath : "";
    std::string bin = binPath ? binPath : "";
    if (paramPath) env->ReleaseStringUTFChars(paramPath_, paramPath);
    if (binPath) env->ReleaseStringUTFChars(binPath_, binPath);
    if (param.empty() || bin.empty()) {
        LOGE("create: empty path");
        return 0;
    }

    auto* m = new Model();
    m->net.opt.use_fp16_packed = false;
    m->net.opt.use_fp16_storage = false;
    m->net.opt.use_fp16_arithmetic = false;
    m->net.opt.use_bf16_storage = false;
    m->net.opt.use_packing_layout = false;
    m->net.opt.num_threads = THREADS;

    int ret = m->net.load_param(param.c_str());
    if (ret != 0) {
        LOGE("load_param failed %d %s", ret, param.c_str());
        delete m;
        return 0;
    }
    ret = m->net.load_model(bin.c_str());
    if (ret != 0) {
        LOGE("load_model failed %d %s", ret, bin.c_str());
        delete m;
        return 0;
    }
    LOGI("kana size model loaded (ncnn, fp32 pinned): %s", param.c_str());
    return reinterpret_cast<jlong>(m);
}

JNIEXPORT void JNICALL
Java_com_holopengin_instantjpdict_KanaSizeNcnn_destroy(JNIEnv*, jclass, jlong handle) {
    delete asModel(handle);
}

/** Logits for [n] windows: win is n*40 byte values, base is n pair indices (0..19). */
JNIEXPORT jfloatArray JNICALL
Java_com_holopengin_instantjpdict_KanaSizeNcnn_batch(
        JNIEnv* env, jclass, jlong handle, jintArray winArr, jintArray baseArr, jint n) {
    Model* m = asModel(handle);
    if (m == nullptr || n <= 0) return nullptr;
    if (env->GetArrayLength(winArr) < n * SEQ || env->GetArrayLength(baseArr) < n) {
        LOGE("batch: win/base shorter than n=%d", n);
        return nullptr;
    }
    std::vector<int> win((size_t) n * SEQ);
    std::vector<int> bases(n);
    env->GetIntArrayRegion(winArr, 0, n * SEQ, win.data());
    env->GetIntArrayRegion(baseArr, 0, n, bases.data());

    std::vector<float> out(n, 0.0f);
    for (int i = 0; i < n; i++) {
        int base = bases[i];
        if (base < 0 || base >= PAIRS) base = 0;

        // Embed takes int indices, so both inputs are 4-byte elements, not floats.
        ncnn::Mat winMat(SEQ, 4u, win.data() + (size_t) i * SEQ);
        ncnn::Mat baseMat(1, 4u, &base);

        ncnn::Extractor ex = m->net.create_extractor();
        ex.input("win", winMat);
        ex.input("base", baseMat);
        ncnn::Mat logit;
        if (ex.extract("logit", logit) != 0 || logit.w < 1) {
            LOGE("batch: extract failed at position %d of %d", i, n);
            return nullptr;
        }
        out[i] = logit[0];
    }

    jfloatArray res = env->NewFloatArray(n);
    if (res != nullptr) env->SetFloatArrayRegion(res, 0, n, out.data());
    return res;
}

}  // extern "C"
