#!/usr/bin/env python3
"""Build the vendored kanji component table (#44 OOV proposals).

KRADFILE decomposes each JIS X 0208 kanji into visual components, which is the only
bridge available between what the recogniser *saw* at an unemittable glyph and what a
dictionary can *offer* for it: at the `呟` gap the head's top-5 is 咳 咬 啦 哮 眩 — all
口/亠 radicals — while 呟 itself is `玄 口 亠 幺`. Sharing components is the filter;
a text n-gram cannot separate 呟 from 咲/働/歩 in context, but the components can.

Input is the EDRDG bundle (EUC-JP), fetched from ftp.edrdg.org/pub/Nihongo/kradzip.zip:

    python3 tools/build_component_table.py --zip /tmp/krad/kradzip.zip \\
        --out-dir app/src/main/assets/components

Output is byte-deterministic (sorted, LF) and written with a PROVENANCE.txt sidecar,
mirroring tools/build_pitch_dict.py. Both kradfile and kradfile2 are merged: they have
different coverage (e.g. 啦 in kradfile2 only), and a component filter wants the union.
"""
import argparse
import hashlib
import io
import zipfile
from pathlib import Path

SOURCE = "http://ftp.edrdg.org/pub/Nihongo/kradzip.zip"
LICENSE = "EDRDG (Creative Commons Attribution-ShareAlike 4.0)"
FILES = ("kradfile", "kradfile2")


def parse_krad(text):
    """`kanji : comp comp …` lines -> {kanji: [components]}."""
    out = {}
    for line in text.splitlines():
        if line.startswith("#") or " : " not in line:
            continue
        kanji, comps = line.split(" : ", 1)
        kanji = kanji.strip()
        comps = comps.split()
        if len(kanji) == 1 and comps:
            out.setdefault(kanji, [])
            for c in comps:
                if c not in out[kanji]:
                    out[kanji].append(c)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--zip", required=True, help="kradzip.zip from EDRDG (EUC-JP)")
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    table = {}
    for name in FILES:
        with zipfile.ZipFile(args.zip) as z:
            raw = z.read(name)
        for kanji, comps in parse_krad(raw.decode("euc_jp")).items():
            slot = table.setdefault(kanji, [])
            for c in comps:
                if c not in slot:
                    slot.append(c)

    lines = [f"{k}:{' '.join(sorted(table[k]))}" for k in sorted(table)]
    data = ("\n".join(lines) + "\n").encode("utf-8")

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    dst = out / "krad_components.txt"
    dst.write_bytes(data)

    with zipfile.ZipFile(args.zip) as z:
        intro = z.read("kradintro").decode("euc_jp", "replace")
    source_date = next((l.strip("# \t") for l in intro.splitlines() if "Version" in l
                        or "Copyright" in l), "")

    prov = (
        "Kanji component table (KRADFILE) — vendored, do not edit by hand.\n\n"
        f"Entries    : {len(lines)}\n"
        f"File       : krad_components.txt\n"
        f"Size       : {len(data)} bytes\n"
        f"SHA-256    : {hashlib.sha256(data).hexdigest()}\n\n"
        f"Source     : {SOURCE}\n"
        f"Files      : {' + '.join(FILES)}\n"
        f"Copyright  : {source_date}\n"
        f"License    : {LICENSE}\n\n"
        "Generated by tools/build_component_table.py — rerun rather than editing.\n"
    )
    (out / "PROVENANCE.txt").write_text(prov, encoding="utf-8")
    print(f"wrote {dst} ({len(lines):,} kanji, {len(data):,} bytes)")
    print(f"wrote {out / 'PROVENANCE.txt'}")


if __name__ == "__main__":
    main()
